steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build and publish to artifactory
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg ARTIFACTORY_USERNAME=ci --build-arg ARTIFACTORY_PASSWORD=$$ARTIFACTORY_PASSWORD .']
    secretEnv: ['ARTIFACTORY_PASSWORD']
options:
  machineType: 'N1_HIGHCPU_8'
timeout: 600s
secrets:
  - kmsKeyName: projects/cerno-245411/locations/global/keyRings/build-keyring/cryptoKeys/artifactory-key
    secretEnv:
      ARTIFACTORY_PASSWORD: CiQACHOf4bS4UdOPyJuxc8ARmVGAs+ypKph71xPtPO4U4OskyNoSRQC3l04NY8SPIRQHn5HIUZ52OoKTKlcidaG/VR6cb7nSDlJxxf1coa9oJeZ8/f2D3UIQz1umCDItNCUX1ZARzrKlNuUFGA==
